all:
  children:
    monitoring:
      hosts:
        vice-monitoring:
          ansible_host: 172.16.20.10
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
        vice-node-exporter-a:
          ansible_host: 172.16.20.11
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
        vice-node-exporter-b:
          ansible_host: 172.16.20.31
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
      vars:
        monitoring_network: 172.20.0.0/16
        prometheus_port: 9090
        grafana_port: 3000
        alertmanager_port: 9093

    discord_bots:
      hosts:
        vice-bot-one:
          ansible_host: 172.16.20.20
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
          bot_instance: 1
          bot_token: "{{ vault_discord_token_1 }}"
        vice-bot-two:
          ansible_host: 172.16.20.21
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
          bot_instance: 2
          bot_token: "{{ vault_discord_token_2 }}"
      vars:
        bot_prefix: "!"
        prometheus_url: "http://172.16.20.10:9090"

    application_servers:
      hosts:
        vice-as01:
          ansible_host: 172.16.20.30
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
      vars:
        nginx_port: 80
        app_environment: production

    automation:
      hosts:
        vice-awx:
          ansible_host: 172.16.20.40
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
        vice-terraform-backend:
          ansible_host: 172.16.20.41
          ansible_user: vice
          ansible_ssh_private_key_file: ../terraform/ssh/vice-monitoring
      vars:
        awx_port: 8052
        terraform_backend_port: 8080

    pve_nodes:
      hosts:
        pve-node-a:
          ansible_host: 172.16.20.100
          ansible_user: root
          ansible_ssh_private_key_file: ../terraform/ssh/pve-root
        pve-node-b:
          ansible_host: 172.16.20.200
          ansible_user: root
          ansible_ssh_private_key_file: ../terraform/ssh/pve-root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    vice_network: 172.16.20.0/24
    monitoring_network: 172.20.0.0/16 